INSTALL_DIR=/home/propeller/src/install
BUILD_DIR=/home/propeller/src/build

BASE_PROPELLER_CLANG_DIR=/home/propeller/src/propeller
CLANG_VERSION=12

PATH_TO_LLVM_SOURCES=${BASE_PROPELLER_CLANG_DIR}/sources

# Build Trunk LLVM
PATH_TO_TRUNK_LLVM_BUILD=${BUILD_DIR}/trunk
mkdir -p ${PATH_TO_TRUNK_LLVM_BUILD} && cd ${PATH_TO_TRUNK_LLVM_BUILD}
cmake -G Ninja ${PATH_TO_LLVM_SOURCES}/llvm-project/llvm \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DLLVM_ENABLE_PROJECTS="clang;lld;compiler-rt" \
    -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
    -DCOMPILER_RT_BUILD_XRAY=OFF \
    -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
    -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}/trunk
ninja -j 4
ls ${PATH_TO_TRUNK_LLVM_BUILD}/bin/clang-${CLANG_VERSION}
ninja install


# Build Instrumented Clang
CPATH=${INSTALL_DIR}/trunk/bin

PATH_TO_INSTRUMENTED_LLVM_BUILD=${BUILD_DIR}/instrumented
mkdir -p ${PATH_TO_INSTRUMENTED_LLVM_BUILD} && cd ${PATH_TO_INSTRUMENTED_LLVM_BUILD}
cmake -G Ninja ${PATH_TO_LLVM_SOURCES}/llvm-project/llvm -DLLVM_TARGETS_TO_BUILD=X86 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=$CPATH/clang -DCMAKE_CXX_COMPILER=$CPATH/clang++ \
    -DLLVM_ENABLE_PROJECTS="clang;lld" \
    -DLLVM_USE_LINKER=lld -DLLVM_BUILD_INSTRUMENTED=ON \
    -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}/instrumented
ninja -j 4
ls ${PATH_TO_INSTRUMENTED_LLVM_BUILD}/bin/clang-${CLANG_VERSION}
ninja install
